### ISSUE TITLE
read_qasm() not recognising some gates 

### ISSUE THREAD

**Issue by kevinab107** [qutip/qutip-qip#208] opened 2023-06-14 08:20 UTC
**Steps to reproduce**
`read_qasm('OPENQASM 2.0;\ninclude "qelib1.inc";\n\ncreg c[2];\nqreg q[2];swap q[0],q[1];\n', strmode = True)
`
**Error**
```
Traceback (most recent call last):

  File ~/anaconda3/envs/qsea/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3508 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[13], line 1
    read_qasm('OPENQASM 2.0;\ninclude "qelib1.inc";\n\ncreg c[2];\nqreg q[2];swap q[0],q[1];\n', strmode = True)

  File ~/anaconda3/envs/qsea/lib/python3.10/site-packages/qutip_qip/qasm.py:902 in read_qasm
    qasm_obj._final_pass(qc)

  File ~/anaconda3/envs/qsea/lib/python3.10/site-packages/qutip_qip/qasm.py:842 in _final_pass
    raise SyntaxError(err)

  File <string>
SyntaxError: QASM: swap is not a valid QASM command.
```

**Comment**

It seems like the qutip parser has predefined qiskit gates in the python code and ignores some gates like swap defined in qelib1.inc. If the mode is “qiskit” only the predefined gates get recognised and many defined ones like swap in qelib1 gets ignored. Hence swap is not recognised 

**Workaround I'm using**: Instead of using the mode qiskit, use a custom mode. Provide the qelib1.inc in the directory. Then the qutip parser will include all the gates in the qelib1.inc. And swap is also parsed. 

**Question**
Am I missing something or is this the intended behaviour? If there is a better way than including the qelib1.inc in the directory, please do let me know.  Also,

**Comment by BoxiLi** [comment] 2023-06-16 07:29
@kevinab107 Thank you very much for the issue and for digging into this. And sorry for the delay. I don't think this is an intended behaviour. If this can be fixed by simply switching to a custom mode and providing the same `qelib1.inc`, then something is wrong in the logic. I have to dig a bit to understand the reason.

If still available, couple you provide a minimal example that reproduces this? Thank you!

**Comment by kevinab107** [comment] 2023-06-20 11:27
@BoxiLi 
The below line should reproduce this. Please do let me know if you need any more details.
```
from qutip.qip.qasm import read_qasm
read_qasm('OPENQASM 2.0;\ninclude "qelib1.inc";\n\ncreg c[2];\nqreg q[2];swap q[0],q[1];\n', strmode = True)
```

**Closed** 2024-04-03 07:29 UTC
